sudo: required

services:
  - docker

env:
  global:
    - REGISTRY_USER=vaidik
    - secure: V3JjvKTdKMbLGQ5q8x/FinrjaaXsVaNTWkYh85Y8s9jClzEvXBzp4cbp9hrTIczi3vQ3wVc3VXWI4yxCk8IkT6iyA7oAUTm4CaemhgTPVMKq5XZY7vCfPJgZW+QzAhcUKV7Rvz1dZf677FlGlwUnqNGdSNIV/j+gLztyS8iaisH9ucafi+fpQCXmX7WHrzL4K01MB1MT1h96R/KpsmvBiItOk4qUYt1HsDurGZ3CnFY0zpX0hQnUrcVZFtVhRBOkqt7sZguRu9hhsSFB39G7aKsHJVMV86KC2MHnDRIF5EDB7Utf5MY7RO/zkfpd/vizmY3B6E6TXGXrsWYzdfpy0zSNiCySH7BNQ+umxUedXBUaKnf1RmvOuXD8Os1iY8uO3LkfuA11+YRXXF0+KKOufH08NnwpUJEMKn9NXthbq1EGzhyzYQPQLppp5AdqRL2imPmKn4iVmjTsKum7fYhittsuok2UCegv0A4heGSESdccHNb/VtXRKbjcNGEwY01vLckd7X+ZYLFvAyeXe2wXyYz04drT+WAAfLiKOE2dReQV78GK20B9jFt9GJ9BlupM+b3EbpuEUlioTDuOFw96w1B11TGlfev/5E7Mhj5spP1Wb1TY7OZwJZfO2k6LtI8Pp5jVGfXeeBsGXOiPLjxeARyOVBevodbffOseKv8sI5k=

before_script:
  - docker pull haskell || true

script:
  - docker build --pull --cache-from haskell --cache-from debian:stretch-slim --tag vaidik/vaidik.in .

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push vaidik/vaidik.in
  on:
    branch: master
